name: facebook_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  video_player: ^1.0.1
  url_launcher: ^5.7.10
  flutter_linkify: ^4.0.2
  emoji_picker: ^0.1.0
  flutter_emoji: ^2.2.1+1
  flutter_launcher_icons: ^0.8.1
  flutter_absolute_path: ^1.0.6
  flutter_slidable: "^0.5.4"
  badges: ^1.1.0
  date_format: ^1.0.6
  cached_network_image: ^1.1.2+1
  transparent_image: ^1.0.0
  font_awesome_flutter: ^8.10.0
  youtube_player_flutter: ^7.0.0+7
  toast: ^0.1.5
  progress_dialog: ^1.2.4
  webview_flutter: ^0.3.14+1
  crypto: ^2.1.5
  connectivity: ^2.0.0
  multi_image_picker: ^4.7.14
  flutter:
    sdk: flutter
    # Check that you have this dependency (added in the previous step)
  shared_preferences: ^0.5.12
  firebase_core: ^0.5.2
  firebase_storage: ^5.0.1
  firebase_auth: ^0.18.3+1
  image_picker: ^0.6.7+12
  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^5.0.2

  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  cloud_firestore: ^0.14.3
  cupertino_icons: ^0.1.2
  provider: ^3.1.0
  dio: 2.0.7
  rxdart: ^0.21.0
  dartin: ^0.1.5
  scoped_model: 1.1.0
  modal_bottom_sheet: 1.0.0+1
#  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/img_lights.jpg
    - assets/images/list_friend/1.jpeg
    - assets/images/list_friend/1.jpg
    - assets/images/list_friend/2.jpg
    - assets/images/list_friend/2.jpeg
    - assets/images/list_friend/3.jpg
    - assets/images/list_friend/4.jpg
    - assets/images/list_friend/5.jpg
    - assets/images/list_friend/6.jpg
    - assets/images/list_friend/7.jpg
    - assets/images/list_friend/8.jpg
    - assets/images/user_account/me.jpg
    - assets/images/user_account/4.jpeg
    - assets/images/list_popular/1.jpg
    - assets/images/list_popular/2.jpg
    - assets/images/list_popular/3.jpg
    - assets/images/list_popular/4.jpg
    - assets/images/list_popular/5.jpg
    - assets/images/list_popular/6.jpg
    - assets/images/list_popular/7.jpg
    - assets/images/list_popular/8.jpg
    - assets/images/list_popular/9.jpg
    - assets/images/list_popular/10.jpg
    - assets/images/fb_favicon.png
    - assets/images/top_background.jpg
    - assets/images/image_signup.png
    - assets/
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
#    - family: Nunito
#      fonts:
#        - asset: assets/fonts/Nunito-Regular.ttf
#        - asset: assets/fonts/Nunito-Black.ttf
#        - asset: assets/fonts/Nunito-Bold.ttf
#    - family: Roboto
#      fonts:
#        - asset: assets/fonts/Roboto-Regular.ttf
#        - asset: assets/fonts/Roboto-Light.ttf
#        - asset: assets/fonts/Roboto-Bold.ttf

