//prefs
const KEY_CURRENT_USER_AVATAR = "KEY_CURRENT_USER_AVATAR";
const KEY_SAVE_LOGIN = "KEY_USER_LOGIN_SAVE";
const KEY_CURRENT_USER_BIRTHDAY = "KEY_CURRENT_USER_BIRTHDAY";
const KEY_CURRENT_USER_EMAIL = "KEY_CURRENT_USER_EMAIL";
const KEY_CURRENT_USER_FIRST_NAME = "KEY_CURRENT_USER_FIRST_NAME";
const KEY_CURRENT_USER_LAST_NAME = "KEY_CURRENT_USER_LAST_NAME";
const KEY_CURRENT_USER_GENRE = "KEY_CURRENT_USER_GENRE";
const KEY_CURRENT_USER_ID = "KEY_CURRENT_USER_ID";
const KEY_CURRENT_USER_PASSWORD = "KEY_CURRENT_USER_PASSWORD";
const KEY_CURRENT_USER_PHONE = "KEY_CURRENT_USER_PHONE";
