//prefs
const KEY_CURRENT_USER = "CURRENT_USER";
const KEY_CURRENT_USER_AVATAR = "CURRENT_USER";
const KEY_CURRENT_USER_BIRTHDAY = "CURRENT_USER";
const KEY_CURRENT_USER_EMAIL = "CURRENT_USER";
const KEY_CURRENT_USER_FIRST_NAME = "CURRENT_USER";
const KEY_CURRENT_USER_LAST_NAME = "CURRENT_USER";
const KEY_CURRENT_USER_GENRE = "CURRENT_USER";
const KEY_CURRENT_USER_ID = "CURRENT_USER";
const KEY_CURRENT_USER_PASSWORD = "CURRENT_USER";
const KEY_CURRENT_USER_PHONE = "CURRENT_USER";
